### ISSUE TITLE
Compression degradation: Terser 4 -> Terser 5

### ISSUE THREAD

**Issue by lega911** [terser/terser#1000]
Hi!
I found that terser 5 makes heavier bundle than terser 4 does:
```
source file: 122754 bytes
terser 4.8.0: 50977 bytes
terser 5.7.0: 52214 bytes
uglyfy 3: 50405 bytes  (just for info)
```
Terser 5 gives +2.4% for the same file, started command: `terser -c -m -o bundle.min.js bundle.js`

Is it expected?

**Comment by fabiosantoscode** [comment]
Compression quality will increase and decrease as bugs are removed, or as some specific optimization turns out to be problematic or too hard to maintain.

So yes, this is kind of normal.

I would usually look into this, but my free time has been directed more towards the SWC port of Terser, so we can have a faster minifier.

Cheers!
