### ISSUE TITLE
Feature: Synchronous API

### ISSUE THREAD

**Issue by overlookmotel** [terser/terser#1026]
**Bug report or Feature request?**

Feature request.

**Description**

For some use cases, it'd be useful to run Terser synchronously.

My particular case is a Javascript serializer [Livepack](https://www.npmjs.com/package/livepack). It has a synchronous API, and I'd like to pass the output through Terser, without having to move the whole library to an async API.

As far as I can see, the only element of Terser which currently requires async is the use of [source-map](https://www.npmjs.com/package/source-map). Therefore, it would not be too difficult to add a `minifySync()` method which uses source-map 0.5.7, while `minify()` continues to use the latest source-map, and leave the rest of Terser unchanged.

Simplest implementation would probably be to use [gensync](https://www.npmjs.com/package/gensync), but if you'd prefer not to add a dependency, it wouldn't be too hard to write some custom branching logic instead.

The solution suggested in https://github.com/terser/terser/issues/385#issuecomment-674524795 - for user to wrap Terser in [deasync](https://www.npmjs.com/package/deasync) - no longer looks workable. deasync [appears to be unmaintained](https://github.com/abbr/deasync/issues/133) and has [major bugs](https://github.com/abbr/deasync/issues/140) on versions of Node >= 12. Personally, I would also prefer not to include a native dependency in my library if I can avoid it.

I would be very happy to implement `minifySync()` and submit a PR, if you'd be willing to receive it.

**Comment by overlookmotel** [comment]
For anyone who needs this, I've published a *very* hacky sync version of terser. It monkey-patches Terser in horrible ways to achieve this, and will probably break in future, so would be much better to implement in Terser itself, but seems to work for now...

https://www.npmjs.com/package/terser-sync

**Comment by fabiosantoscode** [comment]
Hey there!

I empathise with this pain point quite a bit. I hate it when I need to call something async and I have to rework an entire thing to achieve it, even if it's just a few files.

I've [had to deal with this async issue myself](https://github.com/terser/require-terser/blob/master/compile-sync.js) in Terser's functional tests.

However, there was a point in making Terser async, even beyond source maps. You could say it was "prematurely async'd". I've been planning to augment it with rust at some point or another.

This isn't visible because this project moves really slowly, as I don't often find myself with time to look at issues or improve the project.

**Comment by fabiosantoscode** [comment]
It sort of ties into SWC. Eventually I'd like for people to be able to drop this project, and use something way faster and more correct.
