### ISSUE TITLE
Implement ES2022 static initialization blocks?

### ISSUE THREAD

**Issue by Alvarito050506** [terser/terser#1093]
Hello! This relatively new [feature](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Class_static_initialization_blocks) from the next standard [landed](https://caniuse.com/mdn-javascript_classes_static_initialization_blocks) on V8 and SpiderMonkey recently, and I wanted to give it a try, but Terser doesn't seem to recognize it, and I wonder if it could be implemented? Thanks!

**Bug report or Feature request?**
Feature request.

**Version (complete output of `terser -V` or specific git commit)**
`terser 5.9.0`

**Complete CLI command or `minify()` options used**
Not sure, as I'm using it via WebPack.

**`terser` input**
```js
class A
{
    static
    {
        let b = "c";
    }
}
```

**`terser` output or error**
`Unexpected token: punc ({)`

**Expected result**
No errors.

**Comment by LongTengDao** [comment]
Sync from https://github.com/terser/terser/issues/1136

**Version (complete output of `terser -V` or specific git commit)**

5.10.0

**Complete CLI command or `minify()` options used**

default

**Expected result**

That's already stage 4, supported by nodejs, browser and acorn (v8.5.0)

**Comment by tchetwin** [comment]
Terser (and other build time JavaScript tools) operate on "Abstract Syntax Trees" (ASTs) rather than textual source code. This first involves "parsing" to build up a model of the input source before performing transformations and serialising the result.

When new syntax is introduced that doesn't fit the existing parsing rules it will throw rather than blindly proceeding into undefined behaviour territory.

For a very narrow selection of syntactic features (e.g. from one unexpected bracket to the next corresponding closing bracket) you could imagine a mode where a parser just plays dumb and repeats the tokens blindly, but this is very likely to produce invalid output. If your only reference to a variable appeared in that block, Terser might decide it's unused and remove it. It's hard to imagine an outcome where it doesn't cause more problems than it solves.

**Comment by tchetwin** [comment]
Based on past interactions with the project, the underlying goal _is_ to support stage 4 syntax.

Highlighting Issues with that goal in mind is a good idea. It looks like in the past Fábio added the `modern syntax` label: [here](https://github.com/terser/terser/issues?q=is%3Aissue+label%3A"modern+syntax"). `help wanted` could also help.

This could also be applied to (inexhaustive):
* https://github.com/terser/terser/issues/1137
* https://github.com/terser/terser/issues/1124

**Comment by fabiosantoscode** [comment]
Hey there! I read this but didn't interact. I'm prioritizing some of the bugs right now but this is a slow project.

I want to start implementing things that are at stage 3 but I'm not sure I should, as technically they can still change right?

**Comment by peterschuelke** [comment]
I just wanted to stop by and say this feature would be very helpful as I'm experiencing syntax errors while using Apollo Client and Apollo Elements. I'm searching for work arounds as I don't believe this will be done in time to help my project.


`281308 |         window.addEventListener('apollo-controller-disconnected', this.onElementDisconnected);
  281309 |     }
> 281310 |     static { this.is = 'apollo-client'; }
         |           ^ Unexpected token: punc ({)
  281311 |     static { this.observedAttributes = [
  281312 |         'uri',
  281313 |         'validate-variables',
[!] (plugin terser) SyntaxError: Unexpected token: punc ({)`

**Comment by fabiosantoscode** [comment]
I've implemented basic support for this. As far as I can tell, it's pretty solid (though slightly conservative on the code removal side).

Will probably release this monday, if not the next one.
