### ISSUE TITLE
Is there a way to just remove whitespace without doing any other kind of optimizations?

### ISSUE THREAD

**Issue by ghnp5** [terser/terser#1422]
I'm looking to find a tool that all it does is remove whitespace & line breaks, but keeps the rest of the code untouched (variable names, etc).

I'm wondering if `terser` can do that?

The reason I'm looking for it is because I have this project that uses `google/closure-compiler` to minify/obfuscate JavaScript, but it intentionally [adds a line break after every 500 characters](https://developers.google.com/closure/compiler/faq#:~:text=The%20Closure%20Compiler%20intentionally%20adds,effect%20on%20a%20script's%20semantics).

I'm looking to remove the line breaks, and I can easily convert all `\n` to ` `, but then I'd like to remove the spaces. I can't just replace with empty ``, because that causes invalid syntax, as some line breaks really need to be converted to a space.

Thank you!

**Comment by fabiosantoscode** [comment]
Hey there!

You can disable compress and mangle by setting them to false in the [API options](https://terser.org/docs/api-reference/#minify-options-structure) , or by omitting the `-m` and `-c` options in the CLI

There will still be some differences, because some details are not kept when parsing. For instance `() => { return 1 }` will become `() => 1`and unnecessary parens will be removed. However, this is the least transforming you can do with Terser.
