### ISSUE TITLE
terser does not mangle function names

### ISSUE THREAD

**Issue by alanccw** [terser/terser#1488]
Hi,

I check your doc and then invoke terser as below:

terser myscript.js --compress --mangle -o output.js 

The output.js is compressed, but the function names are not mangled. for example, the following function:

`function copyToClipboard(text) {...}`

becomes

`function copyToClipboard(e) {`

The function name is still unchanged. Why?

**Comment by Conduitry** [comment]
Because in script (non-module) mode, `function foo() { ... }` has the side-effect of creating a global variable called `foo`, and Terser doesn't know for sure that no other code is going to be using that. You can either tell Terser to mangle these identifiers anyway with the `toplevel` option, or you can use `module` to tell it that this is going to run as ESM and so these won't actually create global variables it needs to worry about.
