### ISSUE TITLE
Use without NPM

### ISSUE THREAD

**Issue by EndeavourAccuracy** [terser/terser#1518]
Is there any way to use this software without NPM?
For example, can I clone the repository to get started somehow?
I'm asking because apt says installing NPM is 191 packages totalling 151 MB.
jQuery, for example, only requires NPM to build your own versions.
I get that Terser is more complex, but is there really no way around NPM?

**Comment by fabiosantoscode** [comment]
Terser requires NPM, because it relies on dependencies of its own, to deal with source maps.

I recommend installing npm to install Terser, especially if you're going to use more packages. The reason is that it will allow you to pin versions, so that you don't get breakage from things changing or being deprecated. Terser is pretty stable, but still.

However... You can import Terser from a CDN on node 20 with an experimental flag on.

` node --experimental-network-imports main.mjs`

```
// main.mjs
import { minify } from "https://cdn.skypack.dev/terser@5"

const { code } = await minify('console.log(1 + 1)')
```

This isn't the best way to use Terser, because you have to use it through the node API (you can't use the CLI) and you need to rely on a CDN.
