### ISSUE TITLE
(Docs) broken link / markdown issue -- sm-spec

### ISSUE THREAD

**Issue by matthias-ccri** [terser/terser#1576]
On the docs site under [Source map options](https://terser.org/docs/api-reference/#source-map-options), there is this text:

> (see [the spec][sm-spec]) in source map file.

![image](https://github.com/user-attachments/assets/31930559-c478-438d-aff1-af28bccc2f52)

This appears to be a bad output of the markdown, possibly because of the dash character, or perhaps the proximity to the `)` character, idk exactly why. But there is a similar reference style link: `[acorn]` which works fine.

**Comment by fabiosantoscode** [comment]
I think this is related to the fact that the website is generated by cutting up README in line with [these start/end comments](https://github.com/terser/terser/blob/master/README.md?plain=1#L53) to generate .md files.

This breaks these reference-style links because they can end up in a different file. I think I fixed it in https://github.com/terser/terser/commit/430795bbd73bed2737fcd0cd352901889d13b5f7 , I'll wait for the deploy to close this though.

**Comment by fabiosantoscode** [comment]
It's been deployed. Thanks for catching this!
