### ISSUE TITLE
Incorrect code generated when comments are enabled

### ISSUE THREAD

**Issue by evanw** [terser/terser#180]
**Bug report or Feature request?**

Bug report

**Version (complete output of `terser -V`)**

`terser 3.10.12`

**Complete CLI command or `minify()` options used**

`node_modules/.bin/terser example.js --comments all`

**`terser` input**

```js
export function example() {
  if (a == null || b == null) {
    return false
  }

  return (
    // This is a comment
    a.foo === b.foo
  )
}
```

**`terser` output or error**

```js
export function example(){if(a==null||b==null){return false}return
// This is a comment
a.foo===b.foo}
```

**Expected result**

```js
export function example(){if(a==null||b==null){return false}return(
// This is a comment
a.foo===b.foo)}
```

**Comment by kzc** [comment]
I imagine that the bug wasn't noticed earlier because most users minify with `compress` enabled:

```
$ terser example.js --comments all -c
export function example(){return null!=a&&null!=b&&
// This is a comment
a.foo===b.foo}
```

If you want to put together a PR to fix it this is the code in question:

https://github.com/terser-js/terser/blob/master/lib/output.js#L651-L674
https://github.com/terser-js/terser/blob/master/lib/output.js#L467-L544

The trick is not breaking any existing tests.

**Comment by cacheflow** [comment]
I'm happy to try to take this on. @kzc

**Comment by cacheflow** [comment]
About to take a look at this now, but just for clarification the expected result is that the parans should be be kept, correct?

**Comment by cacheflow** [comment]
Thanks! I'll take a look.
