### ISSUE TITLE
Constants not inlined properly

### ISSUE THREAD

**Issue by marvinhagemeister** [terser/terser#215]
**Bug report or Feature request?**
Feature

**Version (complete output of `terser -V`)**
terser 3.14.0-beta

**Complete CLI command or `minify()` options used**
`terser input.js`

**`terser` input**

```js
const A = 1;

function foo(x) {
  switch (x) {
    // Constant A should be inlined here
    case A:
      return 1;
    default:
      return 2;
  }
}
```

**`terser` output or error**

```js
const A=1;
function foo(x) {
  switch(x) {
    case A:
      return 1;
    default:
      return 2
  }
}
```

_(The code above is prettified for readability)_

**Expected result**

If a `const` variable is declared at the global/module scope and is a primitive it is possible to inline it. This is something that we're relying on quite a bit for the next version of [preactjs](https://github.com/developit/preact). Credit goes to @developit for finding this.

```js
function foo(x) {
  switch(x) {
    case 1:
      return 1;
    default:
      return 2
  }
}
```
_(The code above is prettified for readability)_

**Comment by fabiosantoscode** [comment]
Hey there! I figured out why this is happening.

1. The example code you sent needs to be provided the toplevel option or be inside of another function (I'm sure you're doing that already, pointing this out just in case)
2. When a function is moved elsewhere, eg: `function foo() {doSomething()}bar(foo)` -> `bar(function(){doSomething()})`, it looks like the inner function (`foo` here) is not optimized. I believe this is because moving a function does bad things to Terser's notion of what the closures are. If you increase the `passes` option, Terser will recalculate the closures and have a second go at it. Unfortunately this increases the compilation time though.

On this example there's no need to increase the passes to remove the `const` because the function is not moved by Terser:

```javascript
const A=1;                              
                                        
Preact.Something = function foo(x) {    
  switch(x) {                           
    case A:                             
      return 1;                         
    default:                            
      return 2                          
  }                                     
}                                       
```

Here we need to increase the `passes` because Terser moves the function:

```javascript
const A=1;                     
                               
function foo(x) {              
  switch(x) {                  
    case A:                    
      return 1;                
    default:                   
      return 2                 
  }                            
}                              
                               
Preact.Something = foo         
```

I understand this is silly and will keep this issue open to remember to investigate how this can be fixed in the future, so that only one pass is necessary. It might not be possible, but I still want to look into this.

**Comment by fabiosantoscode** [comment]
This has been fixed and will be released in January. Hey, it only took a year! :D

**Comment by marvinhagemeister** [comment]
That's super awesome, thank you so much! :100: Don't mind the time really. Better late than never and we all have a life outside of OSS :wink:
