### ISSUE TITLE
Integrate prepack into compression

### ISSUE THREAD

**Issue by fabiosantoscode** [terser/terser#217]
A lot of what we're doing is already done by prepack. I propose releasing a new major version of terser, where, besides not having a beautify function, uses prepack to replace its eval mechanics, and other things.

**Bug report or Feature request?** Code removal
**Version (complete output of `terser -V`)** a new major
**Complete CLI command or `minify()` options used** any
**`terser` input** any

**`terser` output or error**

(output compressed by terser)

**Expected result**

(output compressed by prepack and terser)

**Comment by chris-morgan** [comment]
After looking through what Prepack does and how it works, I don’t believe that this will work out or achieve what you hope for.

Terser works with symbolic analysis of the code. To take as an example my recently-landed patch to inline spread where possible (#224): Terser now knows that `[a, ...[b, c], d]` is equivalent to `[a, b, c, d]`, and so can perform that optimisation *anywhere*.

But Prepack works by actually *executing* the code (symbolic execution in places, but execution nonetheless). This means that it’s *dangerous*, as it has to make various assumptions about things like all manner of side-effects, and that it only optimises the global flow and specially-marked functions, and that it must be told what the shape of its environment is. This is great for some types of code, but—not to put too fine a point on it—utterly useless for others. Worse than, actually, because it will happily break your code into umpteen smithereens if you look at it funny.

In a little experimentation, it’s downright trivial to get Prepack to generate enormous amounts of code from a tiny source, or to fall over completely. And that’s without considering the environment aspects: while Terser will work on any code, needing no special knowledge of the environment, on typical web code bases Prepack will require quite a bit of help to be able to work *at all*.

Based on my experience with web systems, I expect that Prepack won’t be able to help in *most* of a typical code base. Sure, in the places where it can help, it’s probably going to do a great job (though it *might* do a terrible job for code size or correctness); but most of the code, I don’t think it can do anything with.

Returning to the spread syntax example: sure, in the global scope, Prepack will turn `[1, ...true ? [2, 3] : [], 4]` into `[1, 2, 3, 4]`. But give it that inside a function that isn’t executed on the global code path, and it’ll sit there unoptimised, while Terser will recognise the pattern and fix it.

Its execution engine is also clearly incomplete and/or incorrect: `[...Math.random() < 0.5 ? [2] : [3]]` should yield `[2]` or `[3]` (and thus it could reasonably be rewritten `Math.random() < 0.5 ? [2] : [3]`, but let that pass—Terser wouldn’t catch that either), but Prepack considers that a TypeError.

My analysis could be off the rails—I’ve spent only an hour playing around with it—but if it is correct then Terser would be *significantly* worse for replacing parts of itself with Prepack: it would in fact become literally unusable for most code bases without significant work on their part, which kills it stone dead, because a great thing about Terser is that it requires approximately no effort.

If there is value in tighter integration than purely sequential processing, I’d be interested in seeing what could be done, but I’ve gone from excited about Prepack to pessimistic that it is in any way desirable for most users. It’s rather like the Closure Compiler advanced compression mode—it can be marvellous, but requires careful work by the user to use it.

If there is not value in tighter integration, then just let the people that choose to, add Prepack to their build processes themselves. Suggest it as a valuable tool that is worth experimenting with, by all means; but don’t throw away useful transformations from Terser.

**Comment by fabiosantoscode** [comment]
I don't believe prepack is going to break us in any way, and if it does happen, then you should immediately open an issue. When given Math.random() prepack assumes an abstract value and doesn't execute any further than knowing that either of those is going to be the value. But of course, you will be able to turn off  prepack at will using an option.
