### ISSUE TITLE
Feature request: option to remove whitespace except for newlines.

### ISSUE THREAD

**Issue by koush** [terser/terser#238]
I looked through the terser options, and there doesn't seem to be a way to specify compress behavior for whitespace.

There's a popular embeddable Javascript engine Duktape: https://github.com/svaarala/duktape

It comes with a debugger that supports line based breakpoints. The debugger works great, except on minified code. Minified code typically removes new lines, so all the code is on a single line. This results in the debugger being unable to distinguish one line based breakpoint from any other line based breakpoint. So using any sort of minified code in a dev environment is a no go. Which is a bit of a bummer when using this in resource constrained environment.

There's an open issue on Duktape to support line/col based breakpoints. But I think as a stopgap, it would likely be easier to add an option in terser to not remove line breaks (\n, \r) in minified code. At the moment, whitespace removal seems to be all or nothing with terser.

**Comment by fabiosantoscode** [comment]
Sounds interesting, I'll consider it

**Comment by ca0v** [comment]
I'm having issues with code being out-of-sync and wanted to turn off all minification and simply concat multiple files as-is and generate a .map file with inline source.  That seems impossible even with compress = mangle = false.  It removes whitespace and line breaks.

**Comment by lorenzodallavecchia** [comment]
I just stumbled upon this features request while doing some research.
I think this would be important for `terser@6` because of the coming removal of `beautify`.

Using the `beautify` option is a common workaround to keep code on multiple lines, which improves the support for some downstream tools. For example, one can use webpack with cheap "line-only" source maps and still get full support for debug.

The suggestion of using `prettier` would be prolematic, because prettier does not support consuming and producing source maps like `terser` does. Instead, just keeping newlines (and possibly some other whitespace formatting options) might be enough to replace the need for beautification.

**Comment by lorenzodallavecchia** [comment]
@koush have you found a way to preserve newlines in terser?

**Comment by cseas** [comment]
Just found this issue while trying to retain newlines in terser. 

Setting "format: { beautify: true }" seems to be the only option available to keep newlines. But the beautify option has been marked as *deprecated*. What is the alternative?

**Comment by vdegenne** [comment]
Funny to read this issue where people try to preserve new lines, but I'm trying to find a solution to remove them because it seems that new version of terser is breaking lines by default...

@cseas do you remember the version you were using?

**Comment by fabiosantoscode** [comment]
There is no such thing, currently. Terser works by reading code, transforming it and then emitting it back. It doesn't operate on tokens and have a choice of whether to "remove whitespace" or not. Whitespace is completely removed at the parse step.

The `beautify` option would essentially re-prettify code using its own opinion on how it should look, not how you wrote it originally. I'm removing it because it seems like something `prettier` or another JS formatting package should be doing.

**Comment by vdegenne** [comment]
@fabiosantoscode Sorry I removed my comment and I believe you answered just after it. I found out why I had new lines in my final code, still not sure how but I fixed it and the reason was not terser.

**Comment by fabiosantoscode** [comment]
I saw the e-mail notification, clicked the link, and then I replied to a 1 year old comment like a boomer haha
