### ISSUE TITLE
Bug: `evaluate` option duplicate big strings

### ISSUE THREAD

**Issue by jeetiss** [terser/terser#453]
**Bug report or Feature request?**
Bug

**Version (complete output of `terser -V` or specific git commit)**
terser 4.2.1

**Complete CLI command or `minify()` options used**
default options

**`terser` input**

```
function answer() {
  var __p = '';
  __p += 'big-string';
  return __p
}
```

**`terser` output or error**
```
function answer(){return"big-string","big-string"}
```

**Expected result**
```
function answer(){return"big-string"}
```

**Comment by fabiosantoscode** [comment]
This is a corner case, and only happens when the string is initially empty and because the operator is `+=` (I think).

In these kinds of weird situations, you should increase the `passes` of the compressor. `2` would get around what you're facing and possibly provide other small optimizations in your code too.
