### ISSUE TITLE
a property is left unmangled

### ISSUE THREAD

**Issue by jutunen** [terser/terser#463]
The source file to be minified can be found here: [custom-piano-keys.js](https://raw.githubusercontent.com/jutunen/custom-piano-keys/dbc43398b9fb8e4152225974472e46c56caf85a8/dist/custom-piano-keys.js)

Execute following cmd:
```console
terser custom-piano-keys.js -c -m --mangle-props -o custom-piano-keys.min.js
```
Result: this.strokeWidth is left unmangled

Terser version used: 4.3.1

**Comment by jroessel** [comment]
This is likely because `strokeWidth` is a property on some DOM elements (SVG) that must not be mangled to still work. For safety those are left unmanged, unless you specify `--mangle-props domprops`, as described [here](https://github.com/terser/terser/blob/b1071158ddaac12a9169528f41817f1bf07c50b2/README.md#cli-mangling-property-names---mangle-props).

**Comment by jutunen** [comment]
@jroessel 
I agree. I'm closing this issue.
