### ISSUE TITLE
Feature request: stop embedding functions in big closures

### ISSUE THREAD

**Issue by gdh1995** [terser/terser#500]
**Feature request**

As I've said in https://github.com/terser/terser/issues/350#issuecomment-545784054, I want:

add an option to define a limit X: number, and if a function belongs to a huge closure which has more than X variables and functions, then simply avoid embedding its definition when a current scope is in one of children of the function's scope.

The idea behind it is: if I've hard-code lots of functions (e.g. >= 20 items), then it means I've extracted enough code to avoid allocating temporary function instances frequently, so just skip embedding.

I've written a naive version of this idea in gdh1995@1365bbc and I'm expecting reviews.

**Comment by fabiosantoscode** [comment]
@gdh1995 sorry for not replying for a while, I was busy with some stuff. Your commit looks fine :)

However, I have a few points:

 - I'm not sure why you're checking if the function is an ancestor of the scope of the variable. But if you have a good reason to do that, you should instead check if the function is an ancestor of the scope wherein the SymbolRef is located. You can use the `find_scope(compressor, true)` function to find the nearest scope at the point the compressor is in. From there, you can use `.get_defun_scope()` to get the function scope if you bumped into a block scope and need a function scope.
 - Instead of checking against every type of function, you might want to use `instanceof AST_Lambda` which is the superclass of `AST_Function`, `AST_Defun` and `AST_Arrow`.
 - There's also inlining going on at `def_optimize(AST_Call` which you might want to apply the same logic to. So it might be worth it to put it in a separate function and call it twice.
 - Let's call the option `max_closure_items` instead! I feel it illustrates what the option means to do a bit better.

**Comment by fabiosantoscode** [comment]
If I recall correctly, you were having this problem because you wanted to split your functions into multiple sub-functions, without having too many bindings in the "big" function.

Have you thought about using a block scope to isolate the variables?

```
function big_fn() {
  // part 1
  {
    const bind1 = 4, bind2 = 3
    // use bind1, bind2
  }
  // Part 2
  {
    const bind1 = 4, bind2 = 3
    // use bind1, bind2
  }
}
```

Terser doesn't touch anonymous blocks as long as they have block-scoped variables in them. I don't know how V8 would execute this though.

**Comment by fabiosantoscode** [comment]
If block scopes do work for you, I don't think we want to add this option. New options are costly, in that the documentation should be as *terse* (ahem) as possible, which is why I've been looking for options to remove.

**Comment by gdh1995** [comment]
Thanks.

> split your functions into multiple sub-functions,

Yes, this is what I want.

> block-scoped variables in them

Thanks, but my code needs to satisfy ES5...

> If block scopes do work for you, I don't think we want to add this option.

Never mind if you don't. I've forked terser to use a customized version only in my node_modules, so this feature request is just for discussion purpose.

As for the code details, I have to say I'm not familiar with source code of terser, and then those names were just what I found at that day. If this is not so useful, I think I can leave it there.

If there's no new ideas, feel free to close this topic.

**Comment by fabiosantoscode** [comment]
@gdh1995 from now on, you can use noinline annotation and an IIFE (`/*#__NOINLINE__*/(function () { ... })()`) to section off a function.

That said, in the future we will see less and less browsers in use that don't support ES6, so like the noinline annotation, the block solution is going to be my recommendation from now on :)
