### ISSUE TITLE
Unused Function Variable De-Optimization With Conditional Function

### ISSUE THREAD

**Issue by blakeembrey** [terser/terser#502]
**Bug report or Feature request?** Bug report

**Version (complete output of `terser -V` or specific git commit)** Latest (https://try.terser.org)

**Complete CLI command or `minify()` options used** Defaults.

**`terser` input**

```js
const test = true ? x => x : x => x

export const result = test({ float: "left" }, "unused");
```

**`terser` output or error**

```js
const test=t=>t;export const result=test({float:"left"},"unused");
```

**Expected result**

```js
const test=t=>t;export const result=test({float:"left"});
```

Note: The output above is produced when removing the conditional from `test` declaration, e.g. `const test = x => x`.

Related: Using `let` or `var` removes this optimization as well, so I'm assuming it's somewhat related. I'd love context on why this optimization disappears in the `let` and `const` cases though, my understanding is that it could act the same knowing the variable is not being re-assigned.

**Comment by kzc** [comment]
```
<!-- Note: sub-optimal but correct code is NOT a bug. -->
```
A bug is when the minified code produces a result that is different from the original code. Everything else is a feature request. But in this case it's working as documented:

- `module` (default `false`) -- Pass `true` when compressing an ES6 module. Strict
  mode is implied and the `toplevel` option as well.

- `passes` (default: `1`) -- The maximum number of times to run compress.
  In some cases more than one pass leads to further compressed code.  Keep in
  mind more passes will take more time.

```
$ terser -V
terser 4.3.9

$ cat input.js
const test = true ? x => x : x => x
export const result = test({ float: "left" }, "unused");

$ terser input.js -mc
const test=t=>t;export const result=test({float:"left"},"unused");

$ terser input.js -mc passes=2
const test=t=>t;export const result=test({float:"left"});

$ terser input.js --module -mc passes=2
export const result=(t=>t)({float:"left"});

$ terser input.js --module -mc passes=3
export const result={float:"left"};
```

**Comment by blakeembrey** [comment]
@kzc Feel free to close as needed. I submitted as a bug because it seemed like `const test = true ? statement : statement` should produce the same output as `const test = statement` as input, since they are functionally equivalent (given `true` would never execute the other branch). I may have misunderstand how much knowledge the minifier has of previous statements. I'm also happy to work on this, bug or feature request, as I get time. Since a lot of people typically use only the default configuration, and `true` can be produced in the default Webpack config easily for dead code removal (e.g. `process.env.NODE_ENV === 'production'` is my particular example), I'd be interested in working on this optimization.

**Comment by kzc** [comment]
There's nothing to work on. It's working as designed. 

As the AST is optimized by various compress transforms, more optimization opportunities appear. The optimization stopping point is rather arbitrary and further optimizations come at the expense of greater CPU time. The `passes` option was created to allow users to tune this minification to time ratio. There are rapidly diminishing returns after passes 2 and 3, but you're welcome to set it to Infinity. (Side note: when the AST reaches steady state, `passes` will give up - it rarely goes above 9 in real world code).

It would have been trivial to have made `passes=3` as the default but it would come at the cost of slower minification for all users. The default options are chosen to perform adequate minification in a minimal amount of time for most projects.  [95% of minification in most projects is due to whitespace elimination and symbol mangling](https://github.com/mishoo/UglifyJS2#uglify-fast-minify-mode). That extra 5% of minification performed by `compress` disproportionally accounts for the majority of minify time.

It's puzzling that people are hesitant to set minifier options. This is a compiler and all compilers have settings.  Webpack, Babel, Rollup, Typescript and Closure Compiler are no different in this regard - they all have configurable settings with defaults that they believe are suitable for most users. There is no such thing as one size fits all.  Configurability is key.
