### ISSUE TITLE
reserved option doesn't seem to work in certain cases

### ISSUE THREAD

**Issue by aaron13100** [terser/terser#537]
**Bug report or Feature request?**
Bug report

**Version (complete output of `terser -V` or specific git commit)**
terser 4.4.3

**Complete CLI command used**
terser -c unused=false -m reserved=['ENG','OTHER'] --toplevel -- custom.js 

**`terser` input**
const ENG = {a: 'a'};
const OTHER = 'other';

**`terser` output**
const o="a",OTHER="other";

**Expected result**
const ENG="a",OTHER="other";

**Notes**
I think 'ENG' should not be mangled.
thanks

**Comment by aaron13100** [comment]
`const ENG1 = {};`
`ENG1.a = 'a';` // <-- works
`const ENG2 = {a: 'a'};` // <-- doesn't work

**Comment by aaron13100** [comment]
This seems to only happen when there are no other references within the same file to the the variable in question.

**Comment by fabiosantoscode** [comment]
Hello there!

To achieve the desired effect here, you need to disable `hoist_props` as well because it destroys variables with objects inside, turning them into variables for each of the individual properties. `unused` alone won't cut it in this case.

What you're seeing here is `ENG1 = {...}` being turned into `ENG1_a = '...'` which then gets mangled like anything else because it's no longer called `ENG1` and therefore not reserved.
