### ISSUE TITLE
shorthand object properties with regex mangle produces unexpected results

### ISSUE THREAD

**Issue by osdevisnot** [terser/terser#539]
**Bug report or Feature request?**
Bug Report

**Version (complete output of `terser -V` or specific git commit)**
terser 4.4.3
**Complete CLI command or `minify()` options used**
```
terser index.js --ecma 8 -m --mangle-props regex=/_/
```

**`terser` input**
```js
const vCreateElement = (_name, _props, _children) => ({
  _name,
  _props,
  _children
});
```

**`terser` output or error**
```
const vCreateElement=(e,n,r)=>({t:e,_:n,l:r});
```
**Expected result**
```
const vCreateElement=(e,n,r)=>({e,n,r});
```

Note: both the options when used independently seems to work ok, but produce unexpected result when used together.

**Comment by fabiosantoscode** [comment]
The reason for this behaviour is that mangle and mangle-props work independently and don't really care about each other. Integrating them together so they came up with consistent names would be pretty complicated to do!

In your example, `t` is the result of prop-mangling `_name`. You can make sure the result is correct by using a `_name` property somewhere else. Check this out:

```
const vCreateElement = (_name, _props, _children) => ({
    _name,                                             
    _props,                                            
    _children                                          
});                                                    
                                                       
global._name = 'something'                             
```

When minifying this with your provided options, you will find that the property name of the first property in the object is the same property that's being assigned to `global`. In my case the output is as follows but yours might differ since I won't be releasing Terser until January.

```
const vCreateElement=(e,n,l)=>({l:e,o:n,t:l});
global.l="something";
```

As you can see `l` is used consistently for `_name`.
