### ISSUE TITLE
sub-optimal bracket to dot compression (4.4.3 -> 4.5.0 regression)

### ISSUE THREAD

**Issue by leeoniya** [terser/terser#548]
Hi,

some change in 4.4.3 -> 4.5.0 caused a 206b increase in a build of mine. i have been unable to isolate a minimal repro yet, but it has to do with manual aliasing of method names behaving differently, though the example below does not trigger the issue, it does not behave how i would expect:

input:

```js
(function() {
  var c = "moocow";
  x[c]();
  x[c]();
  x[c]();
  x[c]();
  x[c]();
  x[c]()

  var foobar = "foobar";
  x[foobar]();
  x[foobar]();
  x[foobar]();
  x[foobar]();
  x[foobar]();
})();
```

output:

```js
!function(){var o="moocow";x[o](),x[o](),x[o](),x[o](),x[o](),x[o](),x.foobar(),x.foobar(),x.foobar(),x.foobar(),x.foobar()}();
```

i would expect `var foobar = "foobar";` to get mangled to `var f = "foobar"`, followed by a series of `x[f]();`, but it seems that the mangling logic runs after the bracket -> dot logic, so the original variable name length is used by the compressor heuristics?

while this specific example doesn't trigger what i'm seeing in my code, this is essentially what is going on. terser is now converting all bracket/aliased invocations to dot invocations unconditionally, where before it seemed to do it only when there was not enough uses to retain the aliasing (and it got properly mangled). i suspect that inverting the mangle/compress steps may solve the issue i'm seeing.

9f8294016c722f2b191383f43902cd2ccfec0342 could be the potential culprit?

thanks!

**Comment by leeoniya** [comment]
looks like it's not related to function, just bracket/dot/mangling order. same this observed with:

```js
(function() {
  var c = "moocow";
  x[c] = 1;
  x[c] = 1;
  x[c] = 1;
  x[c] = 1;
  x[c] = 1;
  x[c] = 1

  var foobar = "foobar";
  x[foobar] = 1;
  x[foobar] = 1;
  x[foobar] = 1;
  x[foobar] = 1;
  x[foobar] = 1;
})();
```

**Comment by fabiosantoscode** [comment]
Hello there!

The fact that Terser does not consider name length after compression is a really old issue. What you're probably seeing here, is the fact that keep_fnames now knows to keep function names from constants.

Therefore `const foo = () => ...` keeps its name just like `function foo () {...}` did before. This is intended, in case keep_fnames is enabled.

It might not be keep_fnames though. Losses and gains in compression efficiency in Terser are normal across versions, as some bugs are fixed they may make some of Terser's code more reluctant to inline or otherwise compress things. If you can find a minimal reproduction I can get to that.

**Comment by leeoniya** [comment]
> The fact that Terser does not consider name length after compression is a really old issue.

ok, i'll leave this alone then. i actually get a bit more perf out of the non-bracket version (i'm sure it's easier on the JIT), for which i'm happy to pay the meager size increase (and probably much less after gzip).

> It might not be keep_fnames though.

this is with default settings, so `keep_fnames` is `false`.

thanks for your help!
