### ISSUE TITLE
Convert "a".concat("b","c") to "a"+"b"+"c"

### ISSUE THREAD

**Issue by mappu** [terser/terser#556]
Hi!

Babel takes tagged template literals like 

```javascript
const my_string = `a${b()}c${d()}e`; // ES6
```

and products a series of calls to `String.prototype.concat`:

```javascript
var my_string = "a".concat(b(), "c").concat(d(), "e") // ES5
```

This then gets sent to terser, which does nothing really further with it. But the plus operator would be equivalent and smaller, but terser does not currently perform this transformation

**Bug report or Feature request?**

Feature request

**Version (complete output of `terser -V` or specific git commit)**

terser 4.3.1

**Complete CLI command or `minify()` options used**

**`terser` input**

```javascript
"a".concat(b(), "c").concat(d(),"e")
```

**`terser` output or error**

```javascript
"a".concat(b(), "c").concat(d(),"e")
```

**Expected result**

```javascript
"a"+b()+"c"+d()+"e"
```

**Comment by leeoniya** [comment]
> Babel takes tagged template literals like...and products a series of calls to String.prototype.concat:

😮

**Comment by fabiosantoscode** [comment]
Hey there!

Babel seems to have a few reasons to use `.concat` instead of `+`. The docs link to this issue, which has a pretty good explanation: https://github.com/babel/babel/pull/5791

For the same reasons, Terser can't really change it to use `+`, since doing so would cause a possible change in the outcomes of the input program.

Fortunately, if you know for a fact this doesn't affect you, the relevant plugin (`@babel/plugin-transform-template-literals`) offers a `loose` option which makes it use `+`.

Thanks for this report!
