### ISSUE TITLE
Optimize strings

### ISSUE THREAD

**Issue by Yegorich555** [terser/terser#578]
**Feature request**

Is it possible to join the same strings into single "constant"?

**`terser` input**
```js
const messages = {
  require: "This field is required"
};

const messages2 = {
  require: "This field is required"
};

console.warn(messages);
console.warn(messages2);
```

**`terser` output or error**
```js
const messages = {
  require: "This field is required"
};

const messages2 = {
  require: "This field is required"
};

console.warn(messages);
console.warn(messages2);
```
**Expected result**
Strings optimizing is a big issue because there is no optimizing at all. But we can detect the duplicates of strings and join into a single value. 

Of course in the real code messages are placed in different js files (imported modules, npm packages) and gzip is maybe a better approach for this case. But is it possible to implement this in Terser?

**Comment by fabiosantoscode** [comment]
Hey there!

As you said, gzip can deal with this pretty well!

Terser is built on a principle of being simple and reasonably fast, and I only approve of optimisations that bring a lot of bang for their buck.

I don't think this would be a good optimisation to take on, because the maintenance cost doesn't really outweigh the benefit. Developers usually don't type the same long strings multiple times, and if they do, gzip can deal with it.

**Comment by Attrash-Islam** [comment]
> Developers usually don't type the same long strings multiple times..

Yes, but compilers do. For example `React.createElement("div")` will be repeated a lot in a huge apps

**Comment by benmccann** [comment]
Gzip uses a 32 kB sliding window. If the repeated strings occur within the same 32 kB then gzip can handle it. Otherwise it cannot. While you won't hit this issue in Brotli, over half of sites use gzip compression and more than 10% of sites don't use compression at all. I don't know whether this feature would result in any minor savings or cost for the sites that do use Brotli.
