### ISSUE TITLE
Mangle plugin-proposal-class-properties

### ISSUE THREAD

**Issue by lixtherm** [terser/terser#596]
**Feature: Mangling of properties using "@babel/plugin-proposal-class-properties"**
**Version: 4.6.6 via terser-webpack-plugin@2.3.5**

**minify Options:**
```
terserOptions: {
    mangle: {
        properties: true
    },
    keep_classnames: false
}
```

**`terser` input**

```
class Test {
    _myPropertyToMangle= "foo";
    _myFunctionToMangle= () => {
        console.log(this._myPropertyToMangle)
    }
    writeOutput = () => {
        this._myFunctionToMangle();
    }
}
var x = new Test();
x.writeOutput();
```

**`terser` output or error**
`_myFunctionToMangle` and `_myPropertyToMangle` do not get mangled.

**Expected result**
`_myFunctionToMangle` and `_myPropertyToMangle` should get mangled.

Interestingly they do get mangled if you mark them as private using e.g. `#myPropertyToMangle`

**Comment by fabiosantoscode** [comment]
Nice catch!

**Comment by fabiosantoscode** [comment]
Hey! I think I misunderstood the issue here.

The reason this is happening is because Babel is using a wrapper around Object.defineProperty. Terser can't support this because it would mean reading every function to check if it's a property definer, which is a big performance hit.

Private properties are not being mangled. Babel deals with them itself using WeakMaps and it doesn't write them in the code.

So I'm sorry but I have to close this :snowman: 

Cheers!

**Comment by fabiosantoscode** [comment]
Here's what I'm talking about in terms of output:

[link](https://babeljs.io/en/repl#?browsers=%3E%2030%25&build=&builtIns=false&spec=true&loose=true&code_lz=MYGwhgzhAEAqCmEAu0DeAoa0D6AHATgPa4C80ARAGaGHkDc6AvkA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=stage-2&prettier=false&targets=Electron-1.8%252CNode-8.9&version=7.8.7&externalPlugins=)
