### ISSUE TITLE
How to do nothing but strip comments?

### ISSUE THREAD

**Issue by trusktr** [terser/terser#599]
I'm having a difficult time figuring how to configure Terser to do nothing more than strip comments, and otherwise leave the code untouched. Is this possible?

**Comment by L2jLiga** [comment]
Have you tried to disable compress and set output comments property to false?
```
{
  compress: false,
  mangle: false,
  output: {
    comments: false,
  },
}
```

**Comment by L2jLiga** [comment]
You can also try to configure beautify

**Comment by fabiosantoscode** [comment]
Beautify is going to be deprecated, so I don't recommend using it.

**Comment by fabiosantoscode** [comment]
But Terser basically destroys code style choices like parentheses placement, comment placement, spaces and indentation, and most parsers/transformers will do this too. I don't have any knowledge of a tool which will preserve the code formatting.

If you just wish to remove comments and don't care much for code formatting, you can either:

 - Use terser with the options @L2jLiga mentioned above and pass the output on to prettier.
 - Use acorn and pass the output straight into escodegen. There's no configuration needed since acorn doesn't capture comments by default.
