### ISSUE TITLE
Tree shaking without minification / mangle

### ISSUE THREAD

**Issue by vagonpidarasov** [terser/terser#616]
Is there a way to configure terser to only do tree shaking (dead code removal) without minification?
Duplicate of https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/213

**Comment by fabiosantoscode** [comment]
Yes. You can set the `defaults` option to false, which disabled all the default stuff, making it basically pass-through (it still does remove whitespace, but there's not much we can do about that). Then, you enable the `unused` option, which drops dead code.

For the output part, you'll want to set `comments` to `"all"` so that comments aren't dropped.

**Comment by fabiosantoscode** [comment]
Another thing that might work is to disable optimization on the webpack side, causing terser-webpack-plugin to not be used, but I'm not sure what webpack would do in this scenario.
