### ISSUE TITLE
Does disabling side_effects & sequences compress options reliably support .valueOf modification?

### ISSUE THREAD

**Issue by iskitz** [terser/terser#644]
**Bug report**

**Version (complete output of `terser -V` or specific git commit)**

The version https://try.terser.org/ used on 2020.04.13 03:00-04:00 PST. I couldn't find it listed at the site or in its loaded scripts.

**Complete CLI command or `minify()` options used**
```js
{ compress: {}
, mangle  : {}
, output  : {}
, parse	  : {}
, rename  : {}
}
```

**`terser` input**

```js
;
~
{ re:
    { id:  'next.id@ionify'
    , by: ['mike.lee', 'team']
    , at:  'ionify.net'
    , on:  -7.20160910
    , to:  -7.20190330
    , is:  -0.1
    , it: "generates sequential ids on-demand"
    }

, on    : [['next', 'id']]
, MAX   : Number.MAX_SAFE_INTEGER ||  9007199254740991
, MIN   : Number.MIN_SAFE_INTEGER || -9007199254740991
, ids   : {}

, valueOf
:   function hiphop ()
      { this ["next id"].with = this
      ; delete this.valueOf
      ~ this
      }

, "next id"
:   function nextId (ion)
      { var my   = nextId.with
          , ids  = my.ids
          , name = ion.next
          , f0r  = ion.id.re || (ion.id.re = {})
          , id   = ids [name]

      ; (id >= my.MAX)  && (id = ids [name] = null)
      ; isNaN (id)      && (id = ids [name] = my.MIN)
      ;    f0r.id = name + '.' + id
      ; return ids [name]++
      }
}
;
```

**`terser` output or error**

```js
Number.MAX_SAFE_INTEGER, Number.MIN_SAFE_INTEGER;
```

**Expected result**

```js
~{re:{id:"next.id@ionify",by:["mike.lee","team"],at:"ionify.net",on:-7.20160910,to:-7.20190330,is:-.1,it:"generates sequential ids on-demand"},on:[["next","id"]],MAX:Number.MAX_SAFE_INTEGER||9007199254740991,MIN:Number.MIN_SAFE_INTEGER||-9007199254740991,ids:{},valueOf:function(){this["next id"].with=this;delete this.valueOf;~this},"next id":function nextId(ion){var my=nextId.with,ids=my.ids,name=ion.next,f0r=ion.id.re||(ion.id.re={}),id=ids[name];id>=my.MAX&&(id=ids[name]=null);isNaN(id)&&(id=ids[name]=my.MIN);f0r.id=name+"."+id;return ids[name]++}};
```

**Observations**

```js
{ compress: {side_effects: false, sequences: false}
, mangle  : {}
, output  : {}
, parse	  : {}
, rename  : {}
}
```
produces the expected result but Terser's API compress option documentation doesn't explain why, except for this mention of "side effects" in the **Compiler assumptions** section

>To allow for better optimizations, the compiler makes various assumptions:
>
>- .toString() and .valueOf() don't have **side effects**, and for built-in objects they have not been overridden.

This [ionify](https://api.ionify.net/) code example does implement `.valueOf()` side effects and relies on overriding that in built-in objects for later invocation, but setting these two options to `false` seems to fix the missing outputted code issue despite that.

Why does that restriction exist & why does the `{compress: {sequences: <boolean|number>}}` option cause so much valid code to go missing for truthy values?

Even with these workarounds I still see an issue with this code
```js
{ on:  -7.20160910
, to:  -7.20190330
}
```
being outputted as this with trailing 0's truncated:
```js
{ on:  -7.2016091
, to:  -7.2019033
}
```
The trailing 0’s are significant in this code because they're part of a numeric syntax for representing a date and-or time moment with a leading timezone offset. I understand that the truncated values are still numerically equivalent to their original state,  but the fact that they’re changed (unnecessarily?) stood out. 

**Background**

This issue was prompted by [this related terser minification issue](https://github.com/jsdelivr/jsdelivr/issues/18204) filed with the jsDelivr CDN.

**Comment by fabiosantoscode** [comment]
Hey there!

In short, you're better off disabling compression entirely, and setting the `keep_numbers` output option to true.

I'm updating the documentation for `side_effects` right now because what's there is not a good explanation of what it is supposed to do! In fact, it's supposed to drop side-effect-free code.

Since the whole compressor assumes that `valueOf` and `toString` don't have side effects, `side_effects` thinks it's a good idea to drop your object. You can disable it or enable `expression` to prevent just dropping your object, but every other optimization may just outright assume `valueOf` and `toString` have side effects (or start assuming so in future releases of Terser).

Number values are stored as actual JavaScript numbers, so they don't remember the format they were input in by default. Recently however @L2jLiga added a [PR with a new `keep_numbers` output option](https://github.com/terser/terser/pull/501) to keep the numbers as they were originally input.

In this case, you're doing something very special with JavaScript (reading valueOf and somehow reading trailing zeroes in numbers), so you can't benefit from the compressor. However, most of the size benefit of minifying comes from mangling and removing spaces and comments.

**Comment by iskitz** [comment]
Thanks for the insights @fabiosantoscode. `keep_numbers` works well; happy that’s been added. I *had* tried `{expression:true}` but didn’t see any difference in the output so didn’t bother using it. I was more curious about why the 2 options that did have significant effect did.

The jsDelivr CDN uses terser to auto-compress js files on-demand and doesn’t enable configuring how that happens, so I’ll look to minify the scripts myself and possibly use terser with the config options that give the smallest & most correct result, unless I can find another effective minifier that can handle [ions](https://ion.ionify.net/) & [ionify](https://api.ionify.net) as is.

Great work creating terser. I’ve watched & used many minimizers over the years so I know it’s a lot of work to ensure correctness while best minifying. I wish my special case use of JavaScript was handled but I understand the choice to make trade-offs.

I’m still curious to understand exactly why & how `.valueOf()` & `.toString()` negatively impact or complicate what terser does. It may be useful information in helping me better understand effects I might not have considered. If you can, please point me to or share an explanation with me.

**Comment by fabiosantoscode** [comment]
> Great work creating terser.

Don't give me too much credit :) . This project is a fork of https://github.com/mishoo/UglifyJS2/

> I’m still curious to understand exactly why & how .valueOf() & .toString() negatively impact or complicate what terser does.

That's a great question and something I can't really answer in full. But basically, when minifying, Terser checks if things have side effects all the time. For example, let's suppose `pure_console` is enabled:

```
function x(error) {
  console.log(`An error has occurred: ${error.message}`)
  return 3
}
```

Terser assumes `console.log` here is pure (something you want when you have a bunch of console.log calls for development and none in production), so it removes it. But! If the expression in `error.message` can't be proved to be completely side-effect free, the function becomes:

```
function x() {
  return error.message, 3
}
```

Which may prevent `x()` from being replaced with a simple `3` down the line.

And you may be seeing where I'm getting at here. If `error.message` is an object with `.toString()`, the JS VM will call it and it may have side effects (such as throwing an error or modifying an object somewhere). However, people don't really add side effects to valueOf and toString because it would be confusing, so Terser goes ahead and assumes it doesn't happen, so that it can turn all of that into `return 3`.

Terser does other little shortcuts. For example, it also assumes that you don't use the `document.all` value and `===` compare it to null or undefined. Go ahead and open a console. `document.all == null`. Freaky right? But Terser turns a blind eye. If Terser cared about that, it wouldn't be able to turn `knownVariable === null || knownVariable === undefined` into just `knownVariable == null`.

**Comment by iskitz** [comment]
>Don't give me too much credit :) . This project is a fork of https://github.com/mishoo/UglifyJS2/

😅Fair enough. I knew it was an UglifyJS fork but also know you've done a lot to build **terser** up to what it now is; looks like [you've been at this since 2015](https://github.com/terser/terser/commit/de58b0289d8858b60f5f9aa6e5548fae39109d06)!

>If the expression in error.message can't be proved to be completely side-effect free, the function becomes:
>
>```js
>function x() {
>  return error.message, 3
>}
>```
>And you may be seeing where I'm getting at here. Which may prevent x() from being replaced with a simple 3 down the line. If error.message is an object with .toString(), the JS VM will call it and it may have side effects (such as throwing an error or modifying an object somewhere). However, people don't really add side effects to valueOf and toString because it would be confusing, so Terser goes ahead and assumes it doesn't happen, so that it can turn all of that into return 3. 

Ahhh. I see . . . Thanks for the detailed explanation. It seems there may be an opportunity to continue with **terser**'s approach to restricting `.valueOf()` & `.toString()` overloading while also supporting compressing [ions](https://ion.ionify.net/) which rely on overloading `.valueOf()`.

**ions** use a [specific set of operators](https://github.com/ionify/about/blob/public/ions/ion.md#punctuation) as punctuation before, in-between, and-or after objects in its expressions:

>This example combines fifteen **literal ions** with the seventeen **ion**-compatible bitwise,
arithmetic, relational & equality punctuation operators available:
>
>```js
>~  /example/  -  /punctuation/
>^  ["aesop"]  &  /  stories  /  >>  {are:"ions"}
>*  ["these"]  +  /expressions/  <<  {are:"too" }
>/  ["write"]  %  /them as you/  |   {see:"fit" }
>>  ["using"]  >= /  any of   /  <=  [  "these" ]
><     17      == / compatible/  !=  "operators!"
>```

This means [ion expressions](https://github.com/ionify/about/blob/public/ions/ion.md#form) always have one of these operators preceding and-or following an object reference or literal which makes it much more predictable to know if `.valueOf()` or `.toString()` have been modified for side-effects even in the `console.log (...)` scenario you explained.

[ions](https://ion.ionify.net/) could be used in a similar way to your `console.log ({act:"ion"})` example but they'd still need to explicitly use one of those operators to activate the ion effect since they [intentionally don't & are recommended to not overload `.toString()`](https://github.com/ionify/about/blob/public/ions/ion.md#javascript).

**Given this, is it feasible for terser to support [ion's](https://ion.ionify.net/) specific `.valueOf()` use-case by looking for operator-prefixed & postfixed object expressions?**

**Comment by fabiosantoscode** [comment]
> ions could be used in a similar way to your console.log ({act:"ion"}) example but they'd still need to explicitly use one of those operators to invoke the ion effect since they intentionally don't & are recommended to not overload .toString().

> Given this, is it feasible for terser to support ion's specific .valueOf() use-case by looking for operator-prefixed & postfixed object expressions?

Sadly, due to Terser internals, this isn't easy at all. I think you're still very much better off disabling the compress step entirely, since mangle and removing spaces accounts for most of the possible optimisation. The code is already pretty terse as is!

**Comment by iskitz** [comment]
Got it. Thanks for the great info & conversation @fabiosantoscode!
