### ISSUE TITLE
Terser blowing up without null check

### ISSUE THREAD

**Issue by mephisto83** [terser/terser#666]
I had to add a null check into the minified code or else if just blows up. 

This as in an ElectronIO app.

**Bug report or Feature request?**
![image](https://user-images.githubusercontent.com/7797183/80294078-50f81300-872b-11ea-8a11-3d241114b0f0.png)

**Version (complete output of `terser -V` or specific git commit)**
 "terser-webpack-plugin": "^2.3.5",

**Complete CLI command or `minify()` options used**

**`terser` input**

**`terser` output or error**

**Expected result**

**Comment by jridgewell** [comment]
I'm closing this as not reprodicable, since we can't debug without input code and the options passed to terser. If you can respond with those, we can reopen.

I think you're circling the expression `e.expression.definition()`. Just before that is `e.expression instanceof Vt`, which guarantees that `e.expression` isn't null. So I'm not sure what's throwing.
