### ISSUE TITLE
use variable instead of this

### ISSUE THREAD

**Issue by LongTengDao** [terser/terser#669]
**Bug report or Feature request?** Feature request

**Version (complete output of `terser -V` or specific git commit)** 4.6.3

**Complete CLI command or `minify()` options used**

default

**`terser` input**

```js
function f () {
	const a = this;
	return [ this, a, a, a, this ];
}
```

**`terser` output or error**

```js
function f(){const t=this;return[this,t,t,t,this]}
```

**Expected result**

```js
function f(){const t=this;return[t,t,t,t,t]}
```

**Comment by avdg** [comment]
Terser doesn't track assignments of variable, it only mangles names to shorter versions.

Even if terser did, in this case it would actually make more sense to replace everything to `this` if the file would be send over with gzip. This is because gzip can compress repeating words better and terser can get rid of an assignment (`const a = this`).

**Comment by fabiosantoscode** [comment]
I agree.

Is this a real use case? If someone types `const t = this` they're probably going to keep using `t`.

Terser isn't meant to achieve perfect compression all the time.

**Comment by LongTengDao** [comment]
I see, thank you!

(The real use case is render code compiled from vue sfc templte -- the code is generated by compiler, so it's not so clever, ;)
