### ISSUE TITLE
bug with __PURE__ option

### ISSUE THREAD

**Issue by LongTengDao** [terser/terser#672]
**Bug report or Feature request?** Bug report

**Version (complete output of `terser -V` or specific git commit)** try.terser.org

**Complete CLI command or `minify()` options used**

```
{
	compress: {
		side_effects: false,
	},
	mangle: false,
	output: {
		comments: () => true,
	},
}
```

**`terser` input**

```js
function f () {
  /*#__PURE__*/a();
  /*#__PURE__*/b();
}
```

**`terser` output or error**

```js
function f(){
a()}
```

**Expected result**

```js
function f(){/*#__PURE__*/a(),/*#__PURE__*/b()}
```

---

There are multi problems in the sample.
1. `b()` disapear
2. a newline apear
3. the doc said output.beautify is default for `true`, but in my test, it seems default to be false
4. I can't keep `/*#__PURE__*/a()` (don't removing both comment and calling), to leave it open to downstream user to make the decision. Currently, I must decide, whether to treeshake the pure calling, or miss the comment and it will never be treeshaked.

**Comment by fabiosantoscode** [comment]
1. `b()` disappearing is what `/*__PURE__*/` is for! If something is pure, and you call it and don't use the result, it did absolutely nothing, so it can be removed. It's odd that `a()` is still there though, probably would disappear with more passes I think.
2. This is probably because of the comments being annotations, and being removed by default. Interesting that it's happening but I don't think it's too important to fix.
3. Long standing bug :/ CLI works different from API in this regard. I meant to fix this with Terser 4 by removing beautify entirely or passing beautify options in a different command line flag, but I didn't fix it.
4. `preserve_annotations` output option will preserve annotation comments which remain. There's currently no way to tell terser to keep pure functions around for historical reasons that are hard to fight at this point.

**Comment by LongTengDao** [comment]
1. `side_effects` is used to control whether we see `/*#__PURE__*/` as a special comment, even `/*#__PURE__*/` can't be reserved currently, the `b()` should be reserved. (BTW: more `passes` won't make `a()` disappear.)
2. Year, that's not important, ignore it for the moment. (BTW: more `passes` even won't make the newline disappear.)
3. Oh, I see. This is a problem when users don't know it, but nothing when users know it.
4. Ok, it can be waited.

The first one is really a bug, and I found it's also in `uglify-js`, so I will open an issue there to resolve that together.

**Comment by gaoxiaoliangz** [comment]
I would also want terser to preserve `/*#__PURE__*/`. I am developing a library, and I want my users to use my lib and also take advantage of webpack tree shaking.
