### ISSUE TITLE
Do not minify nodejs bundle

### ISSUE THREAD

**Issue by paulmillr** [terser/terser#680]
Could you disable minification for node.js releases? It's impossbile to debug and audit right now.

There is zero reasons to minify the node release.

**Comment by fabiosantoscode** [comment]
The package is really large as is (1.6mb just the dist folder). The current status quo is to use https://www.npmjs.com/package/source-map-support to enable source maps in node and have proper stack traces.

I do admit it's terrible for debugging, though :/ but it's pretty ironic to distribute a minifier that's so large!

My ultimate goal is to distribute everything as ES6 modules, allowing node and the browser to import them and increasing transparency, debuggability and patchability (am I the only one who adds console.log statements to files in node_modules?).

I've been thinking we can do these things to help:

 - Disable mangling entirely, so that make sense, and so variable names in errors are complete
 - Add an option which makes terser require('source-map-support') before it starts.

**Comment by fabiosantoscode** [comment]
Related to #700 (Terser 5 will be shipped as a dual package)

**Comment by tchetwin** [comment]
> The current status quo is to use https://www.npmjs.com/package/source-map-support to enable source maps in node and have proper stack traces.

Does this status-quo change with: [`--enable-source-maps`](https://nodejs.org/docs/latest-v12.x/api/cli.html#cli_enable_source_maps)? Blog post here: https://medium.com/@nodejs/source-maps-in-node-js-482872b56116

Not aware that that would change anything from point-of-view of terser though.

**Comment by fabiosantoscode** [comment]
@tchetwin that's great! We can change Terser's recommendation in the issue template and the readme, which would help people understand the root of the problem and fill in more accurate issues when things go wrong.

I've opened #732, thank you for bringing this up as I didn't know about it!
