### ISSUE TITLE
Is it possible to minimize words like functions, createElement

### ISSUE THREAD

**Issue by t0lkman** [terser/terser#681]
Is it possible to minimize words like function, createElement etc
I see in the result they keep repeating...

Are there any options to make function=foo,createElement=ce for example?

**Comment by fabiosantoscode** [comment]
Hello there!

`function` is a language keyword. In a lot of cases, you can make use of the `unsafe_arrows` option to turn ES5 functions into arrow functions. It's unsafe, because if you try to access their prototype, they don't have one. However if you don't use prototypes or classes anywhere in your code, it should be safe to use.

`createElement` is part of the `document` (I think React has one such property as well), and it's not possible to minify properties that belong to code Terser doesn't control. If it was under your control you could use property mangling, but it's a very advanced feature with a lot of pitfalls.
