### ISSUE TITLE
Mangle named parameters

### ISSUE THREAD

**Issue by privatenumber** [terser/terser#707]
### Bug report or Feature request?
Feature request:

Mangle object property names if Terser can detect that they're only being used as function parameters w/ object-spread and the function is not exported.

I haven't thought this through completely, but I'm thinking this could be possible under some strict conditions.

### Motivation
[Named parameters using object-spread](https://twitter.com/rauschma/status/1263112404600225792?s=20) is a semantic alternative to bare function parameters and it's not uncommon to see them in code lately.

eg. Named parameters are used in [isomorphic-git](https://github.com/isomorphic-git/isomorphic-git). 424 instances of `{fs:` and 421 instances of `gitdir:` exist in the [minified distribution](https://unpkg.com/isomorphic-git@1.4.0/index.umd.min.js) (imagine a longer property name).

#### Input
```js
function fnWithNamedParameters({ paramA, paramB }) {
    return paramA + paramB
}

fnWithNamedParameters({ paramA: 1, paramB: 2 })
```

#### Output
```js
function a({ b, c }) {
    return b + c
}

a({ b: 1, c: 2 })
```

or even better

```js
function a(b, c) {
    return b + c
}

a(1, 2)
```

**Comment by fabiosantoscode** [comment]
Hello there!

This is a duplicate issue for sure, but I can't find the original.

You're right in thinking that this should be possible in strict conditions. However, Terser's code currently doesn't do any flow analysis, and I'm not very keen on starting to do so, since it would be pretty hard!

Additionally, this optimization would be pretty fragile due to the strict conditions you mentioned.

So I think I should close this, in the interest of keeping Terser small and bug free.
