### ISSUE TITLE
Missed inlining opportunity when function called 3+ times

### ISSUE THREAD

**Issue by shicks** [terser/terser#708]
**Bug report or Feature request?**
Feature request

**Version (complete output of `terser -V` or specific git commit)**
4.7.0

**Complete CLI command or `minify()` options used**
```
terser -c passes=50 input.js
```

**`terser` input**

```
(function(){

/*@__INLINE__*/
function define(name, defVal) {
  return defVal;
}

const UNUSED = /*@__INLINE__*/ define('UNUSED', false);
const DEBUG = /*@__INLINE__*/ define('DEBUG', false);
const ASSERT = /*@__INLINE__*/ define('ASSERT', DEBUG);

console.log(ASSERT ? 'foo' : 'bar');

})();
```

**`terser` output or error**
```
!function(){function define(name,defVal){return defVal}const DEBUG=define(0,!1),ASSERT=define(0,DEBUG);console.log(ASSERT?"foo":"bar")}();
```

**Expected result**
```
console.log("bar");
```

**Discussion**
I'm continuing exploration on #653, and my current approach is to start with something that is not at all configurable - basically, a function where you specify the defaults directly in the source and terser will just use those values.  My thought is that once this works, then I can worry about how to customize it - possibly with a pre-pass of some sort.

In general this seems to work pretty well, even across modules (though not so well across multiple chunks).  But it seems to fall apart if there are 3 or more calls to the function - terser just stops inlining it.  Given that I've explicitly marked the definition and all call sites as `/*@__INLINE__*/`, I'm not sure how much clearer I can be that I really want it to be inlined.

**Comment by shicks** [comment]
Interestingly, any simpler functions (i.e. the 1-arg identity function, or one that always returns undefined) do continue to inline even with more calls.

**Comment by fabiosantoscode** [comment]
Interesting bug!

I've given more thought about the issues you've been putting out. I agree that this is a real problem, and it stings quite a bit. I really want to be able to define constants at the export level, but that will have to be done at the bundler level I think. Perhaps a rollup and webpack plugin which can patch exports should be created! Or maybe it already exists.

About this specific issue:

I'm looking into it right now. I implemented a tentative fix, which treats a `/*#__INLINE__*/` comment as a signal of "I know exactly what I'm doing, just pull the function in and shut up". The result is as follows (with 1 pass):

```
!function() {
    defVal = !1;
    var defVal;
    let ASSERT = function(name, defVal) {
        return defVal;
    }(0, function(name, defVal) {
        return defVal;
    }(0, !1));
    console.log(ASSERT ? "foo" : "bar");
}();
```

The code is simple, because Terser doesn't need to check whether the function can be inlined (you just told it that it can). However, it quite obviously duplicates the function over and over again. This is because after the first inline, `defVal` is being pulled out to the inline target scope and used as a `var`. There must be a better way.

**Comment by fabiosantoscode** [comment]
On second thought, I think this solution isn't so bad. The inlining can be improved upon later, with further improvements to Terser (a separate inlining+dead-code-removal pass using a proper graph library comes to mind). If you absolutely want something to be inlined, you're getting what you want, and for now, you can increase passes. In the example I showed above, just 2 passes fit the bill.

**Comment by shicks** [comment]
Thanks for looking into that.  That seems quite reasonable - indeed, an explicit inline request does seem like an advanced feature that can be dangerous if you don't _really_ want it inlined.

**Comment by fabiosantoscode** [comment]
I've added it to the Terser 5 branch. Alpha versions for it will come up eventually.
