### ISSUE TITLE
More intelligent eval bailout (dead branches)

### ISSUE THREAD

**Issue by mischnic** [terser/terser#711]
**Bug report or Feature request?**

sub-optimal output

**Version (complete output of `terser -V` or specific git commit)**

4.7.0

**Complete CLI command or `minify()` options used**

`terser -cm --toplevel`

**`terser` input**

1. 
```js
if(false) {
  eval("X");
}

let unused = 1;
```

and 

2. 
```js
function f() {
 eval("X");
}

let unused = 1;
```

**`terser` output or error**

1.  `let e=1;`
2. `function f(){eval("X")}let unused=1;`

**Expected result**

1. It appears that the eval-bailout check happens before pruning dead branches. I'd expect empty output
1. I'd expect empty output. `f` is unused, and after that, the eval is gone and `unused` can be removed as well.

**Comment by fabiosantoscode** [comment]
Hey! Thanks for reporting :)

Your 2. case got deoptimized. In fact, in the future, I can't guarantee that even 1. will work.

Such deopts not only affect the function scope where `eval` was found, but also every scope that `eval` might possibly change variables in.

The idea is that accomodating for users using `eval`, `width` and other obscure corners of the language, is limited to making sure the code keeps working correctly. Minifying code using such things is really hard to accomplish, causes a lot of bugs, and the benefits are small since `eval` is rarely ever used.

The workaround, if you can, is to use global eval. `(0, eval)(anything)` is guaranteed not to modify local variables, so the deopt doesn't happen.

**Comment by mischnic** [comment]
Yeah, I was already somewhat expecting this to be too complex to fix.

(In this case, we was investigating why some bundles generated by [Parcel](https://github.com/parcel-bundler/parcel) where not being compressed at all by Terser. It's the same "obscure corners that we are forced to support"-situation caused by a dependency on a 2-year old firebase version.)
