### ISSUE TITLE
Feature request: drop call of noop functions

### ISSUE THREAD

**Issue by xiaoxiangmoe** [terser/terser#721]
**Feature request**
 
**`terser` input**
```js
// Just do it with a simple string union to simplify things
function isBigCat(animal)  {
  switch (animal) {
    case "tiger":
    case "lion":
      return false;
    case "dog":
    case "autobus":
      break;
    default:
      unreachable(animal)
  }
    return true
}

// this is a noop function and call of this should be dropped
function unreachable(data) { 
  return;
}
```

**`terser` output**

```js
function isBigCat(e){switch(e){case"tiger":case"lion":return!1;case"dog":case"autobus":break;default:unreachable(e)}return!0}function unreachable(e){}
```
**Expected result**
```js
function isBigCat(n){switch(n){case"tiger":case"lion":return!1}return!0}function unreachable(n){}
```

---

related issue:

https://github.com/microsoft/TypeScript/issues/38881

**Comment by fabiosantoscode** [comment]
Hello there!

Empty functions are dropped, but not how you might think. First, they are inlined, and then they are dropped.

However, they can't be inlined if they're on the toplevel of the file and you didn't specify `toplevel` or `module`. If you do (and prevent isBigCat from being dropped as well by console.log'ing it or something) you will find that your `unreachable` function is not called.

PS: I will weigh in on the linked issue because it annoys me very much at my day job :)
