### ISSUE TITLE
Dead code detection for static class members not working; breaking tree shaking

### ISSUE THREAD

**Issue by maximilianMairinger** [terser/terser#724]
**Bug report or Feature request?**

Feature request

**Version (complete output of `terser -V` or specific git commit)**

4.7.0

**Complete CLI command or `minify()` options used**

**`terser --warn --compress --mangle --module test.js`**

*test.js*

```js
class A {}
A.staticProp = "A"
```

**Explaination**

This is the code emmited by typescript etc. when using static class properties. 

```ts
class A {
  static staticProp = "A"
}
```

[playground](https://www.typescriptlang.org/play/index.html?ssl=3&ssc=2&pln=1&pc=1#code/MYGwhgzhAECC0G8CwAoa0IBcyYJbA2z2AAUAnAewAdoBeaAIlgdQF8g)

By not removing class A (which could be huge) from the output, treeshaking in combination with bundlers (like webpack) wont work. Which can be very unintuetive considering that the following (workaround) code gets deteced as dead as expected. The difference here is only in style not in function.

```ts
class A {
  
}
let A_staticProp = "A"
```

This is especially unintuetive since this input gets detected as dead:

```js
let a = {
  
}  
a.ok = "okok"
```

As of my understanding using a class with static members vs. a normal object does not have any implications on bahaviour, at least for this example. But maybe removing static members as above could break some code I am not considering though.

**`terser` output**

```js
(class{}).staticProp="A";
```

**Expected result**

```js

```

Same as with `class A {}` as input

**Comment by fabiosantoscode** [comment]
In this case, Terser is avoiding the assumption that setting a property could have side effects.

Someone might've written this code:

```
Object.defineProperty(Function.prototype, 'staticProp', {
    set() {                                              
        throw new Error('You set me!')                   
    }                                                    
})                                                       
```

Or caused any sort of side effect. This makes your code actually not removable.

I understand how annoying this can be, and I don't really agree with it. However, the community keeps coming up with ways to subvert expectations. Abusing `~` to cause side effects, using property get and set to cause side effects or throw errors.

But seeing that classes are not as abused as objects, in that people are *probably* not going to abuse getters and setters, it's fair to open an exception.

**Comment by clydin** [comment]
While there is probably not much terser can do about this, I think TypeScript's `useDefineForClassFields` option should also be mentioned here.  When enabled, TypeScript will use `[[Define]]` semantics instead of `[[Set]]` to create properties and to align with the [specification](https://github.com/tc39/proposal-class-fields#public-fields-created-with-objectdefineproperty).  This will result in the following for the example above:
```
    class A {
    }
    Object.defineProperty(A, "staticProp", {
        enumerable: true,
        configurable: true,
        writable: true,
        value: "A"
    });
```
This will not be removed since `Object.defineProperty` can technically throw.  Although in the TypeScript case, compilation error checking should cover the cases that would cause it to throw.  A pure annotation can also not be used directly on the `Object.defineProperty` call since that would always remove the call and break usage of the class.

Babel will also generate similar code for static properties by default:
```
class A {}

_defineProperty(A, "staticProp", 'a');
```
`_defineProperty` is a helper function that calls `Object.defineProperty`.  Babel has a `loose` option which, when enabled, will cause `[[Set]]` semantics to be used.
