### ISSUE TITLE
How to use terser.minify v5 in env where async is not allowed?

### ISSUE THREAD

**Issue by freethebit** [terser/terser#772]

**Comment by L2jLiga** [comment]
You can try to use [deasync](https://www.npmjs.com/package/deasync)

**Comment by fabiosantoscode** [comment]
@freethebit I'm not sure if you mean when async/await is not a syntax option, but I'll explain for future googlers anyway:

When you don't have access to async/await (can't use modern syntax for any reason) you can use .then

```javascript
minify(/* minify arguments */)
  .then(
    ({ code, map }) => /* do your thing with the compiled code */,
    error => /* process the error */
  )
```

However, if you've successfully imported Terser some compilation must happen because Terser itself uses async/await.

If what you mean is that you need to call terser synchronously (for example on some callback or map function which really needs to run synchronously), there's not much that can be done about that. Because source-map is now written WASM, minify() needed to be turned into an async function.

**Comment by fabiosantoscode** [comment]
I sympathize with you on this one :) I also didn't want to make Terser async.

@L2jLiga's package seems legit, thanks mate! It will go right into my mental toolbox next time I need to do something like this. My previous option was to stick the async code in an [isolated-vm](https://www.npmjs.com/package/isolated-vm) but that doesn't come with node I/O APIs so it would've been cumbersome.
