### ISSUE TITLE
Lossless Property Mangling

### ISSUE THREAD

**Issue by brainkim** [terser/terser#798]
Feature request

**Version**
5.2.1

**Complete CLI command or `minify()` options used**
`terser --mangle --mangle-props -- foo.js`

**`terser` input**
`foo.js`
```js
class Foo {
  constructor() {
    this.aLongName = 1;
    this.anotherLongName = 1;
  }
}

const foo = new Foo();
foo.aLongName = 2;
delete foo.anotherLongName;
console.log(foo.aLongName, foo.anotherLongName);
```

**`terser` output**
```js
class Foo{constructor(){this.o=1;this.s=1}}const foo=new Foo;foo.o=2;delete foo.s;console.log(foo.o,foo.s);
```

**Proposed output**
```js
var o="aLongName",s="anotherLongName";class Foo{constructor(){this[o]=1;this[s]=1}}const foo=new Foo;foo[o]=2;delete foo[s];console.log(foo[o],foo[s]);
```

Thanks for creating and maintaining the Terser project. Maybe this is more of a question than an issue. I was trying to think of better ways to mangle props in libraries while maintaining readable code. The problem with prop mangling as it currently stands is two-fold:
1. Library authors either need to tell the user to mangle specific prop names, or they need to mangle the props themselves.
2. The mangled code will produce objects of different shapes than the source code, so if you accidentally use both mangled and unmangled versions of the same code, the two codebases might “talk past each other.”

My question is, have JavaScript minifiers like terser considered using square bracket property accessors to mangle props instead? The way it would work is that all props in code are declared as strings at the top of the file, and then we replace all dot notation reads and writes to properties with the equivalent bracket notation and variable. This would require no configuration by the app or library author, and would preserve the property names at runtime, meaning you’d never have to worry about inconsistent mangling.

Is this feasible for terser? Am I missing something obvious which makes this type of transform impossible or ineffective?

**Comment by fabiosantoscode** [comment]
Something like this has been cited before as something we should do.

I replied with my concerns about performance, but to be honest they are unfounded. It's not reasonable to assume performance without a real-world test of a reasonably sized app.

That said, mangling properties turns all your objects into a bunch of unintelligible junk, which is not cool if you have a public API. There should be a safe option.

If this is going to be done, it should require the toplevel or module option to be set. This is because doing this would involve creating new variables at the top level. It would also have to be performed after all compression has occurred because if it happened before it would hinder the compression efficiency for other transforms.

**Comment by fabiosantoscode** [comment]
Related issue: #590

**Comment by brainkim** [comment]
Ahhh seems like a duplicate, my bad! My take on the perf stuff is that we’re not gonna know the actual impact on performance until someone tries it!
