### ISSUE TITLE
Parallel assignments are not optimally compressed

### ISSUE THREAD

**Issue by curiousdannii** [terser/terser#804]
I tried looking for a similar issue, sorry if this has been raised before.

**Bug report or Feature request?** Sub-optimal code suggestion

**Version (complete output of `terser -V` or specific git commit)** REPL

**Complete CLI command or `minify()` options used** default options

**`terser` input**

```
var a = {}
if (Math.random() > 0.5)
{
  a.verylongpropertyname = 1000
}
else
{
  a.verylongpropertyname = 2000
}
```

**`terser` output or error**

```
var a={};Math.random()>.5?a.verylongpropertyname=1e3:a.verylongpropertyname=2e3;
```

**Expected result**

```
var a={};a.verylongpropertyname=Math.random()>.5?1e3:2e3;
```

Obviously there could be very complicated branches which can't be easily optimised, but I'd expect that it's a fairly common pattern to have two branches which both assign to the same variable or property.

**Comment by fabiosantoscode** [comment]
This happens because reordering is going on.

By default `Math.random()` is considered to be impure (unknown function). And `a.verylongpropertyname` as well (getters may have side effects).

Since turning `x ? a = b : a = c` into `a = x ? b : c` would place `a` before `x`, if either is even possibly going to cause a side effect it's not safe to reorder them.

**Comment by curiousdannii** [comment]
Ah, there is indeed a difference between assigning to variables and to properties. Sorry.
