### ISSUE TITLE
How can I use RegExp in terser?

### ISSUE THREAD

**Issue by pccai** [terser/terser#812]
![image](https://user-images.githubusercontent.com/2232794/92084829-88be4800-edfa-11ea-99bc-ce2acd288e2b.png)

when runing after terser:

![image](https://user-images.githubusercontent.com/2232794/92084871-9542a080-edfa-11ea-9681-82b94baf9130.png)

but RegExp cannot work.

**Bug report or Feature request?**

**Version (complete output of `terser -V` or specific git commit)**

**Complete CLI command or `minify()` options used**

**`terser` input**

**`terser` output or error**

**Expected result**

**Comment by avdg** [comment]
Did you test the code before passing it to terser?

**Comment by fabiosantoscode** [comment]
Terser doesn't read what you pass in to RegExp and assumes it's correct :) compressing the regular expression's language is hard and the gains would be tiny anyway.

Your browser (if it's IE11 or Safari) might not support the modern `?<=` you inserted there.

**Comment by fabiosantoscode** [comment]
I assume that's the problem here.

Terser will not read your regex at all, in fact it only interprets `/abc/` style regex just enough to find the end of it and move on to the next thing. And `RegExp` is considered to be a global variable so it doesn't even remotely consider it.

I'm closing this on the assumption that the code was incorrect being passed in. Either way, this doesn't follow the issue template.
