### ISSUE TITLE
Add another project under this org?

### ISSUE THREAD

**Issue by rodrigograca31** [terser/terser#817]
Found another project that maybe should be under the terser organization: https://github.com/pioug/gulp-html-minifier-terser

It's a fork of https://github.com/jonschlinkert/gulp-htmlmin which [hasn't been updated to use terser](https://github.com/jonschlinkert/gulp-htmlmin/issues/103)

[As you can see](https://github.com/jonschlinkert/gulp-htmlmin/compare/master...pioug:master) @pioug fixed that and [released a new lib](https://www.npmjs.com/package/gulp-html-minifier-terser)

I think it would be better for the community if this project was under the terser organization.

Thoughts? 💭

**Comment by pioug** [comment]
Thanks for proposing this! I like the idea 👍  
Though I still wish we could somehow get the original npm package from @jonschlinkert and update it 💦

**Comment by jonschlinkert** [comment]
Is there an outstanding PR?

**Comment by rodrigograca31** [comment]
@jonschlinkert 

There's this one: https://github.com/jonschlinkert/gulp-htmlmin/pull/104

or we can make a new one from @pioug fork:
https://github.com/jonschlinkert/gulp-htmlmin/compare/master...pioug:master

**Comment by fabiosantoscode** [comment]
Hey there!

Sorry for not responding earlier.

I don't think that this package would be a good fit for the terser organisation, since it's more of gulp adapter, and because there are so many different build tools, this org would be full of different adapters for Terser, html-minifier-terser and anything else we come up with in the future.

Besides this potential issue, I think this org should be focused on more lower-level tools.

**Comment by fabiosantoscode** [comment]
Since around 4 months ago I've been thinking a lot about the amount of glue code in our community, to stitch tools together, and it's always seemed to me like things should be simpler than that.

The Terser org might have a meta-adapter in the future (here's [my first attempt at one](https://www.npmjs.com/package/scatterbrain) ) but I think individual adapters for combinations of tools are a lot of work to maintain over time, due to changing versions, changing APIs, etc.

**Comment by rodrigograca31** [comment]
You got great points @fabiosantoscode 

I don't think the Gulp org wants plugins under their org either so it seems this project will stay its own repo.
