### ISSUE TITLE
Bug: Compress inlines a function call with the wrong value for a variable coming from its context

### ISSUE THREAD

**Issue by mutedchaos** [terser/terser#837]
**Bug report or Feature request?**
Bug report

**Version (complete output of `terser -V` or specific git commit)**
5.3.2

**Complete CLI command or `minify()` options used**

    npx terser --compress -- repro.js

**`terser` input**
repro.js:
```js
function outer() {
  let shouldBeTrueWhenCallingInner = true
  inner()
  shouldBeTrueWhenCallingInner = false
  // Uncommenting the line below still has same issue, while the function is not inlined, the variable is
  // inner()

  function inner() {
    console.log('Should be true:', shouldBeTrueWhenCallingInner)
  }
}
outer()

```

**`terser` output or error**
```js
function outer(){let shouldBeTrueWhenCallingInner=!0;console.log("Should be true:",!1),shouldBeTrueWhenCallingInner=!1}outer();
```

**Expected result**
```js
function outer(){let shouldBeTrueWhenCallingInner=!0;console.log("Should be true:",!0),shouldBeTrueWhenCallingInner=!1}outer();
```
or
```
function outer(){let shouldBeTrueWhenCallingInner=!0;console.log("Should be true:",shouldBeTrueWhenCallingInner),shouldBeTrueWhenCallingInner=!1}outer();
```

Having `inner` declared above `shouldBeTrueWhenCallingInner = false` seems to work around this issue.

**Comment by fabiosantoscode** [comment]
This one has me quite perplexed.

It seems like you can avoid it by disabling the `evaluate` option, but you'll gain a lot of bytes in the output.

**Comment by puzrin** [comment]
> It seems like you can avoid it by disabling the `evaluate` option, but you'll gain a lot of bytes in the output.

Option helps, but not desied. Let me explain our context:

- We have [pica](https://github.com/nodeca/pica/tree/master/dist) build, created with borwseify + webworkify. Inernally, it knows how "convert" own sources to webwoker
- We have [image-blob-reduce](https://github.com/nodeca/image-blob-reduce) with rollup/terser, using pica inside.

Poblem is, teser "optimizes" commonjs wrapper [emulator of `require`], been in main context (it uses typeof to check helpers and drops fallback code). Then, when code is collected by pica for webworker, if fails to execute, because required fallack was dropped.

**Comment by fabiosantoscode** [comment]
Fixed as part of https://github.com/terser/terser/issues/1306
