### ISSUE TITLE
Unnecessary Parentheses Inserted Around Functions Used As Arguments

### ISSUE THREAD

**Issue by davehawkins4f** [terser/terser#839]
**Bug report or Feature request?**

Bug report

**Version (complete output of `terser -V` or specific git commit)**

5.3.2

**Complete CLI command or `minify()` options used**

terser

**`terser` input**

```
f(function a() {}, function b() {});
f(() => {}, () => {});
```

**`terser` output or error**

```
f((function a(){}),(function b(){}));f(()=>{},()=>{});
```

Additional parentheses have been inserted around the functions used as arguments but not the lambdas.

**Expected result**

```
f(function a(){},function b(){});f(()=>{},()=>{});
```

No additional parentheses inserted.

This is similar to issue 281, but for functions rather than lambdas. While the generated code is just sub-optimal, this is causing a problem for other tools that read the code. In particular, it confuses the requirejs optimizer, r.js, and causes it to generated invalid code in some circumstances:
```
define(function () {});
->define((function (){})); // terser
->define(('module_name',[],function (){})); // r.js incorrectly inserted arguments
```

**Comment by fabiosantoscode** [comment]
Hey there! This can be controlled by setting the wrap_func_args format option to false. This was added and set to true by default because it increases performance.

It's interesting that arrow functions are not wrapped, I should fix this.

Regarding other tools interpreting code, I don't mean to be harsh but this is valid JavaScript which engines in the wild run faster than without the (). If a proper parser is used and not string operations, there should not be an issue finding the function. Perhaps filing a bug report on this tool would be a good thing.

**Comment by davehawkins4f** [comment]
Thanks for the quick update.

I completely agree that it's not the responsibility of terser to provide workarounds for problems in other tools. My intention was merely to give an example of how it was causing a problem and thus some indication of impact. Ideally r.js would be fixed, but given it doesn't look like it's been updated in two years, I'm not hopeful that will be the case. Fortunately there's a workaround, so I don't need to switch off the performance improvement.
