### ISSUE TITLE
Simplify `let a = undefined;` to `let a;` (same for `var`)

### ISSUE THREAD

**Issue by WofWca** [terser/terser#869]
**Bug report or Feature request?**
Feature request

**Version (complete output of `terser -V` or specific git commit)**
`v5.3.8`

**Complete CLI command or `minify()` options used**

```js
{
  compress: {
    unsafe: true,
  },
  mangle: {},
  output: {},
  parse: {},
  rename: {},
}
```

**`terser` input**

```js
let a = undefined;
```

**`terser` output or error**
```js
let a=void 0;
```

**Expected result**
```js
let a;
```

Not a huge JS expert, but looks they're equivalent. There's an ESLint rule for this: https://eslint.org/docs/rules/no-undef-init.

**Comment by fabiosantoscode** [comment]
Sounds good.

I've added this for just `let`, not `var`, because `var` works differently depending on whether a variable has been initialized yet.

**Comment by lillallol** [comment]
@fabiosantoscode

I think an uninitialized variable should be used by terser by default instead of `void 0`. 

For example this:
```
export let transactionTreeNode = () => ({a : undefined,b : undefined,c : undefined,d : undefined,e : undefined})
```
should become something like:
```
let u;export let transactionTreeNode=()=>({a:u,b:u,c:u,d:u,e:u});
```
and not this:
```
export let transactionTreeNode=()=>({a:void 0,b:void 0,c:void 0,d:void 0,e:void 0});
```
as it is currently done in the REPL.

**Comment by fabiosantoscode** [comment]
I agree. And a lot more constants too. But I should do some thorough benchmarks to figure out if that's a good idea.

You see, "void 0" is optimized by JS engines at parse time, before any sort of optimization that would look at existing variables. It's incredibly fast.

**Comment by lillallol** [comment]
@fabiosantoscode So terser cares not only about minification but also about parsing time. We care about minification because we want to reduce server costs but also because the responses will be delivered faster. We care about parsing time because we want to reduce time to responsive for our website, and that because this gives better SEO. Is there something more that I am missing?

Although I am not really experienced we these stuff I think for some cases, people might prefer to reduce server costs instead of time to first responsive, and hence  there should be an option for choosing between `void 0` and a non initialized variable.
