### ISSUE TITLE
Feature request: Annotation to ignore parts of a JS file.

### ISSUE THREAD

**Issue by mangelozzi** [terser/terser#887]
**Feature request**

In [black](https://github.com/psf/black) (a python code formatter), one can disable formatting with a special comment:
```py
# fmt: off
foo = "this line will not be formatted"
# fmt: on
```

With Django or PHP/Wordpress, one may be required to enque variables into the javacsript. Terser then falls over at this none standard templating syntax (which will be replaced at run time by the server). 

An [annotation](https://github.com/terser/terser#annotations) for disabling formatting the line would allow one to use Terser in these scenarios:
For example:
```js
      /*#__FORMAT_OFF__*/{% load static %}/*#__FORMAT_ON__*/
```

In the above snippet, `{% load static %}` is a tag which tells the Django template loader to load the static tags (which help determine the static dir at runtime). A static file is often hashed so it can have long life headers, e.g. `{% static 'pwa/sw.js' %}` is converted to `"/static/pwa/sw.fa348fe8a8dbc89a.js";`

**Comment by brandon942** [comment]
The 2 lines are the same except for the string content. But the the string content is not changed by terser. What's the issue?
You could split the variable declarations out of the script that is to be minified, which is supposed to be a static file.

**Comment by mangelozzi** [comment]
{% load static %}

> The 2 lines are the same except for the string content. But the the string content is not changed by terser. What's the issue?
> You could split the variable declarations out of the script that is to be minified, which is supposed to be a static file.

Fair point, okay my easy/contrived example would not break Terser, so I updated it to the actual problem I am having.

**Comment by brandon942** [comment]
@mangelozzi So you have a server pre-processed template file, not a standard javascript file and you want to minify the javascript in that template file. Again, I would split out the dynamic parts and feed that into your static script file via function arguments or globals. I think what you're trying to do is bad because pre processing a larger than necessary mostly static file on each request needlessly increases the workload on the server. To me that's pure energy waste.   

But if you insist on templating your script file then you don't need terser to do that for you. You can simply add placeholders for your template stuff and turn the script file into a template after you minify it. For example
```
// ...
TEMPLATE_STUFF_X_HERE(`anything`); // that's treated like an undeclared variable and won't be touched by a minifier, it must be unique.
// ...
```
Then you just replace your placeholders with whatever template stuff you want there to be. In my example you could use the regular expression ``` /TEMPLATE_STUFF_X_HERE\(`([\S\s]+?)`\);/mg ``` and replace it with the first capturing group $1
Note if you add `()` to make the placeholder look like a function call - or if you add dots in between to make it look like you're accessing properties or getter functions, then the minifier will make sure to keep the position of your placeholder the same.

**Comment by bjesus** [comment]
@fabiosantoscode would you be interested in a PR that implements this or a similar behavior? We also need the ability to ignore certain parts of the code because our JS uses some templating to generate.

**Comment by fabiosantoscode** [comment]
Hello there!

This is infeasible to implement in Terser. The internal AST format would have to be augmented to allow arbitrary non-standard code, and then a whole lot of transforms would need to ignore it when checking references, purity etc.

As an alternative in Django (I miss it so much :) ) and other templating languages, when inserting templated code, one can do the following:

Place it in a variable in another script tag, as such:

```
<script>
window.staticFiles = {% load static %}
</script>
```

This would place the value globally and make it available for the rest of your code as `window.staticFiles` or just `staticFiles`. You wouldn't minify this script tag of course, but others would be good to minify.

Alternatively, with some clever escaping one could insert this in a `JSON.parse("{{{ ... }}}")` call, though it requires you to escape through JSON, JS and HTML.
