### ISSUE TITLE
bundle.min.js is not minified

### ISSUE THREAD

**Issue by da0ka** [terser/terser#904]
https://cdn.jsdelivr.net/npm/terser/dist/bundle.min.js
file name has ".min", but not minified(later than v4.8.0).

**Comment by fabiosantoscode** [comment]
When releasing that version, I removed minification because it messed with stack traces, making filing bug reports harder for everyone.

To make transition easier, the name stayed the same.

This was mentioned in passing in [the changelog](https://github.com/terser/terser/blob/master/CHANGELOG.md#v500)
