### ISSUE TITLE
Cloudflare Worker Compatibility

### ISSUE THREAD

**Issue by samouri** [terser/terser#925]
**summary**
[Cloudflare Workers](https://blog.cloudflare.com/introducing-cloudflare-workers/) are a super fast function-as-a-service provider. They currently have a restriction that [no worker code may use dynamic eval](https://developers.cloudflare.com/workers/runtime-apis/web-standards#javascript-standards) (`new Function(code)`, or `eval("code")`). Unfortunately, `terser` uses dynamic eval in a single location.

https://github.com/terser/terser/blob/83c027e728e289a0ae1b87dc52bf3ea594387d8f/lib/ast.js#L69

My questions for the maintainers:
-  Do you know if it is possible to write this functionality in a way that doesn't use dynamic eval?
- If yes, are you open to a PR for this?

**Comment by fabiosantoscode** [comment]
Well, this is kind of a macro to generate our AST. It's quite fast because functions returned from `eval` are able to be optimized by V8

If it doesn't have a negative performance or memory impact, then I'm open to a PR. I suppose this will involve very repetitive class constructors.

I do like the idea of running Terser in a CF worker. Are you going to serve minified modules for usage in browser `import`? You're quickly going to find that Terser uses a lot of memory even for small payloads, and that you'd prefer to use a rust based minifier for the job, like SWC.

Right now I'm working on a very early version of a WASM wrapper for Terser, that can chunk up JS into smaller tokens and feed it into Terser web workers.

**Comment by tyvdh** [comment]
I too am super interested in this functionality. Would love to help test stuff as it would be helpful.

**Comment by fabiosantoscode** [comment]
There's still one instance of `new Function()`, in lib/propmangle.js, but it doesn't have an argument. Let me know if it causes problems and I'll reopen the issue.

Thanks to @sgoo for the clean fix

**Comment by sgoo** [comment]
Thanks for merging! 

The code in propmangle is fine for us because all of the globals its looking for are present so it never calls `new Function()`.

But I did check and even the arg less `new Function()` will result in `EvalError: Code generation from strings disallowed for this context` if eval has been disabled in v8 so this could be an issue for other runtimes.

**Comment by jridgewell** [comment]
Couldn't that `new Function()` just be `function () {}` expression?

**Comment by fabiosantoscode** [comment]
No problem! If further issues are found with running Terser on a cloudflare worker (or other workers) let me know. I never tested anything of the sort.

**Comment by Manu1400** [comment]
FYI: Soon, you can use "eval()" and "new Function()" in global scope within Cloudflare workers! https://github.com/cloudflare/workerd/pull/4142

source: https://x.com/yagiznizipli/status/1922385647085502688
