### ISSUE TITLE
`comments: "some"` should work with `preserve_annotations: true`

### ISSUE THREAD

**Issue by mischnic** [terser/terser#968]
**Bug report or Feature request?**

Feature request

The default setting of `comments: "some"` shouldn't remove pure comments with `preserve_annotations: true`.

So `"some"` should not only include `@license` and `@preserve` but also `@__PURE__` and `#__PURE__`.

**Version (complete output of `terser -V` or specific git commit)**

5.6.1

**Complete CLI command or `minify()` options used**

```js
{
  module: true,
  compress: false,
  format: {
    preserve_annotations: true,
    comments: "some"
  }
}
```

**`terser` input**

```js
// something
export const X = /*#__PURE__*/ (() => 1);
```

**`terser` output or error**

```js
export const X=()=>1;
```

**Expected result**

```js
export const X=/*#__PURE__*/()=>1;
```

**Comment by fabiosantoscode** [comment]
Hello! This issue is really a disagreement on design. The "some" comments isn't meant to be read by another tool after, just to preserve license comments and comments starting in `!`.

If you'd like to, you can extend the regex for "some", which is `/@preserve|@lic|@cc_on|^\**!/i` (and should really be in the docs :) )
