### ISSUE TITLE
Can't get terser to work: no output, or terser not even found if without -g

### ISSUE THREAD

**Issue by SatStackr** [terser/terser#970]
I'm on macOS Catalina 10.15.6. If I do this:
```
npm install terser
terser --version
```

I'm getting `zsh: command not found: terser`

Instead, if I do:
```
npm install -g terser
terser --version
```
I'm getting `terser 5.6.1` which seems OK. 
(There were no errors during the installation step)

But then I do this:
```
terser --compress example.js
```

And nothing happens. No errors, no output, no prompt, it's just stuck and I have to press Ctrl+C. This happens regardless of whatever contents are in example.js or even if example.js doesn't even exist.

Am I doing something wrong or am I misunderstanding how terser is supposed to work?

Also is there a way to get it working without `install -g` ? Because I prefer to not install things globally

**Comment by fabiosantoscode** [comment]
Hello there! Installing Terser without `-g` will install it to your local node_modules folder.

This is not added to your PATH and therefore is not available to be called by your shell (but it is available in package.json scripts because they add `node_modules/.bin` to your PATH).

The apparent freeze is due to the (admittedly not very user friendly) default that terser will minify its input from stdin. It's actually waiting for you to type out the javascript and close the stdin stream (by pressing control+D) or pipe some other command into terser (like `cat file.js | terser`).

The more user friendly way to use terser from the command line is to run `terser file.js -mc -o file.min.js` (the file needs to come first and the options after).
