### ISSUE TITLE
Feature request : Test coverage based dead code deletion / tree shaking

### ISSUE THREAD

**Issue by 1000i100** [terser/terser#972]
I build a 100% unit tested static package.
It inline it's dependencies.
I run the unit test with coverage `c8 ava` before terser and i run again `ava` after to verify if the minified version still pass all the tests.

With my use-case, i would love to use coverage report to apply a brutal dead code deletion on all dependencies code not executed (all my code is executed during test).

Is it possible to add this in terser ? as an unsafe optimization ?
Do you think it's a good idea ?

**Comment by 1000i100** [comment]
PS : here is my code:

https://framagit.org/g1/g1lib.js/
and the build process : 
https://framagit.org/g1/g1lib.js/-/blob/main/package.json

**Comment by fabiosantoscode** [comment]
Very interesting idea! 

However, while I agree with your personal use case, I imagine that it's not very common. Minification is way more common in frontend apps, which rarely have 100% test coverage.

A very compelling way to achieve what you're talking about is something like prepack, which uses symbolic execution to precompute as much as it can (way more than what terser does), and remove dead code very effectively (because it doesn't pick up on what it didn't execute).

That said, if I were to implement something like what you describe, I wouldn't implement it in Terser, but instead integrate it into a proper coverage tool.

This way it's easier to keep track of the source location of removable things, without dealing with imprecisions caused by multiple different parsers. Then, removing unused code becomes a matter of using something like magic-string to remove things (or replace with null to keep syntactic validity) without parsing everything again.
